# Generated by Django 5.1.4 on 2025-01-04 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Data_From', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
